[Lilka]
extends = esp32_base
board = lilka
board_build.mcu = esp32s3
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
upload_protocol = esptool
build_flags =
  ${esp32_base.build_flags}
  -I variants/lilka
  -D LILKA_BOARD
  -D BOARD_HAS_PSRAM=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D PIN_BOARD_SDA=2
  -D PIN_BOARD_SCL=42
  ; ---- bat ----
  -D PIN_VBAT_READ=3
  -D ADC_MULTIPLIER=1.33
  ; ---- buttons ----
  -D UI_HAS_JOYSTICK=1
  -D PIN_BUZZER=11
  -D PIN_USER_BTN=5
  -D JOYSTICK_LEFT=39
  -D JOYSTICK_RIGHT=40
  -D PIN_BACK_BTN=6
  -D USER_BTN_PRESSED=LOW
  ; ---- ST7789 IPS display, 240x280 ----
  -D DISPLAY_CLASS=ST7789LCDDisplay
  -D DISPLAY_WIDTH=240
  -D DISPLAY_HEIGHT=280
  -D DISPLAY_ROTATION=1     
  -D DISPLAY_SCALE_X=2.1875 ; 280 / 128 logical canvas width
  -D DISPLAY_SCALE_Y=3.75   ; 240 / 64  logical canvas height
  -D PIN_TFT_CS=7
  -D PIN_TFT_DC=15
  -D PIN_TFT_SCL=18
  -D PIN_TFT_SDA=17
  -D PIN_TFT_RST=-1
  -D PIN_TFT_LEDA_CTL=46
  -D PIN_TFT_VDD_CTL=-1
  -D TFT_OFFSET_X=0
  -D TFT_OFFSET_Y=20
; ---- LoRa module ----
  -D P_LORA_NSS=13
  -D P_LORA_RESET=48
  -D P_LORA_BUSY=43
  -D P_LORA_DIO_1=44
  -D P_LORA_SCLK=14
  -D P_LORA_MISO=47
  -D P_LORA_MOSI=21
  -D SX126X_RXEN=12
  -D SX126X_TXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_MAX_POWER=22
  -D LORA_TX_POWER=22
;  -D SX126X_REGISTER_PATCH=1  ; 0x8B5 RX-improvement patch, confirmed applied by Meshtastic on this E22 module

build_src_filter =
  ${esp32_base.build_src_filter}
  +<helpers/ui/ST7789LCDDisplay.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/ui/buzzer.cpp>
  +<../variants/lilka>

lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  end2endzone/NonBlockingRTTTL @ ^1.3.0

; ==================== SX1268 build  ====================

[env:Lilka_sx1268_companion_radio_ble]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456     ; change this before flashing a real device
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${Lilka.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1268_companion_radio_wifi]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D WIFI_SSID='"myssid"'    ; change to your WiFi network
  -D WIFI_PWD='"mypwd"'      ; change to your WiFi password
  -D WIFI_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${Lilka.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1268_companion_radio_usb]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D ENABLE_USB_INTERFACE
build_src_filter =
  ${Lilka.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1268_repeater]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D DISPLAY_CLASS=ST7789LCDDisplay
  -D ADVERT_NAME='"Lilka Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter =
  ${Lilka.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  ${esp32_ota.lib_deps}

[env:Lilka_sx1268_room_server]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -D ADVERT_NAME='"Lilka Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"meow"'
  -D USE_SX1268
  -D RADIO_CLASS=CustomSX1268
  -D WRAPPER_CLASS=CustomSX1268Wrapper
  -D DISPLAY_CLASS=ST7789LCDDisplay
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = 
  ${Lilka.build_src_filter}
  +<../examples/simple_room_server>
lib_deps =
  ${Lilka.lib_deps}
  ${esp32_ota.lib_deps}

; ==================== SX1262 build  ====================

[env:Lilka_sx1262_companion_radio_ble]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456     ; change this before flashing a real device
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${Lilka.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1262_companion_radio_wifi]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D WIFI_SSID='"myssid"'    ; change to your WiFi network
  -D WIFI_PWD='"mypwd"'      ; change to your WiFi password
  -D WIFI_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${Lilka.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1262_companion_radio_usb]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -I examples/companion_radio/ui-new
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D ENABLE_USB_INTERFACE
build_src_filter =
  ${Lilka.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:Lilka_sx1262_repeater]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D DISPLAY_CLASS=ST7789LCDDisplay
  -D ADVERT_NAME='"Lilka Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter =
  ${Lilka.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
lib_deps =
  ${Lilka.lib_deps}
  ${esp32_ota.lib_deps}

[env:Lilka_sx1262_room_server]
extends = Lilka
build_flags =
  ${Lilka.build_flags}
  -D ADVERT_NAME='"Lilka Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"meow"'
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D DISPLAY_CLASS=ST7789LCDDisplay
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = 
  ${Lilka.build_src_filter}
  +<../examples/simple_room_server>
lib_deps =
  ${Lilka.lib_deps}
  ${esp32_ota.lib_deps}
