#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef ARDUINO
  #include <Arduino.h>
#else
  #define PROGMEM
#endif

// Arial font tables whose upper half (0x80..0xFF) is laid out as Windows-1251
// instead of ISO-8859-1, so they carry the full Cyrillic alphabet. Codes
// 0x20..0x7F are identical to the stock ArialMT_Plain_* tables.
// Generated by tools/gen_cyrillic_font.py.
extern const uint8_t ArialMT_Plain_16_Cyr[] PROGMEM;
extern const uint8_t ArialMT_Plain_24_Cyr[] PROGMEM;

// Unicode -> Windows-1251 lookup tables, sorted by code point.
extern const uint16_t CYRILLIC_UNICODE[] PROGMEM;
extern const uint8_t CYRILLIC_CP1251[] PROGMEM;
extern const uint16_t CYRILLIC_MAP_LEN;

// OLEDDisplay FontTableLookupFunction that decodes UTF-8 into the tables above.
// Feed it one byte at a time (it is stateful across a multi-byte sequence) and
// it returns the font table index, or 0 for "nothing to draw yet / unsupported".
char cyrillicFontLookup(const uint8_t ch);

// Copies UTF-8 `src` into `dest`, dropping control characters and never cutting
// a multi-byte sequence in half. Replaces DisplayDriver::translateUTF8ToBlocks()
// for drivers using the fonts above, which need the UTF-8 left intact.
void cyrillicCopyUTF8(char* dest, const char* src, size_t dest_size);
