[mmm_promicro]
extends = nrf52_base
board = promicro_nrf52840
build_flags = ${nrf52_base.build_flags}
  -I variants/modular_mesh_maker
  -D MMM_PROMICRO
  -D RADIO_CLASS=CustomLR2021
  -D WRAPPER_CLASS=CustomLR2021Wrapper
  -D USE_LR2021
  -D P_LORA_POWER_EN=2
  -D P_LORA_DIO_1=11
  -D LR2021_IRQ_DIO=9
  -D P_LORA_NSS=13
  -D P_LORA_SCLK=12
  -D P_LORA_MOSI=14
  -D P_LORA_MISO=15
  -D P_LORA_RESET=10
  -D P_LORA_BUSY=16
  -D LR2021_TCXO_VOLTAGE=3.3f
  -D RF_SWITCH_TABLE
  -D LORA_TX_POWER=22
  -D PIN_BOARD_SCL=7
  -D PIN_BOARD_SDA=8
  -D PIN_OLED_RESET=-1
  -D PIN_USER_BTN=6
; GPS RX and TX are defined backwards by Meshcore
; PIN_GPS_RX is output to GPS uart
; PIN_GPS_TX is input from GPS uart
  -D PIN_GPS_RX=4
  -D PIN_GPS_TX=3
  -D PIN_GPS_EN=5
  -D GPS_BAUD_RATE=115200
  -D ENV_INCLUDE_GPS=1
  -D ENV_INCLUDE_AHTX0=1
  -D ENV_INCLUDE_BME280=1
  -D ENV_INCLUDE_BMP280=1
  -D ENV_INCLUDE_INA3221=1
  -D ENV_INCLUDE_INA219=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/sensors>
  +<../variants/modular_mesh_maker>
lib_deps= ${nrf52_base.lib_deps}
  adafruit/Adafruit SSD1306 @ ^2.5.13
  adafruit/Adafruit INA3221 Library @ ^1.0.1
  adafruit/Adafruit INA219 @ ^1.2.3
  adafruit/Adafruit AHTX0 @ ^2.0.5
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit BMP280 Library@^2.6.8
  stevemarple/MicroNMEA @ ^2.0.6

[env:mmm_promicro_repeater]
extends = mmm_promicro
build_src_filter = ${mmm_promicro.build_src_filter}
  +<../examples/simple_repeater>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
build_flags =
  ${mmm_promicro.build_flags}
  -D ADVERT_NAME='"Modular Mesh Maker Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps = ${mmm_promicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

[env:mmm_promicro_repeater_bridge_rs232_serial1]
extends = mmm_promicro
build_src_filter = ${mmm_promicro.build_src_filter}
  +<../examples/simple_repeater>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/bridges/RS232Bridge.cpp>
build_flags =
  ${mmm_promicro.build_flags}
  -D ADVERT_NAME='"RS232 Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
  -D WITH_RS232_BRIDGE=Serial1
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL1_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL1_TX
  -UENV_INCLUDE_GPS
;  -D BRIDGE_DEBUG=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps = ${mmm_promicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

[env:mmm_promicro_room_server]
extends = mmm_promicro
build_src_filter = ${mmm_promicro.build_src_filter}
  +<../examples/simple_room_server>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
build_flags = ${mmm_promicro.build_flags}
  -D ADVERT_NAME='"Modular Mesh Maker Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
  -D DISPLAY_CLASS=SSD1306Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps = ${mmm_promicro.lib_deps}
  adafruit/RTClib @ ^2.1.3

[env:mmm_promicro_terminal_chat]
extends = mmm_promicro
build_flags = ${mmm_promicro.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${mmm_promicro.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps = ${mmm_promicro.lib_deps}
  densaugeo/base64 @ ~1.4.0
  adafruit/RTClib @ ^2.1.3

[env:mmm_promicro_companion_radio_usb]
extends = mmm_promicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${mmm_promicro.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D DISPLAY_CLASS=SSD1306Display
  -D ENABLE_USB_INTERFACE
; NOTE: DO NOT ENABLE -->  -D MESH_PACKET_LOGGING=1
; NOTE: DO NOT ENABLE -->  -D MESH_DEBUG=1
build_src_filter = ${mmm_promicro.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${mmm_promicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:mmm_promicro_companion_radio_ble]
extends = mmm_promicro
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags = ${mmm_promicro.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D DISPLAY_CLASS=SSD1306Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${mmm_promicro.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps = ${mmm_promicro.lib_deps}
  adafruit/RTClib @ ^2.1.3
  densaugeo/base64 @ ~1.4.0

[env:mmm_promicro_sensor]
extends = mmm_promicro
build_flags =
  ${mmm_promicro.build_flags}
  -D ADVERT_NAME='"Modular Mesh Maker Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D DISPLAY_CLASS=SSD1306Display
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${mmm_promicro.build_src_filter}
  +<helpers/ui/SSD1306Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/simple_sensor>
lib_deps =
  ${mmm_promicro.lib_deps}

[env:mmm_promicro_kiss_modem]
extends = mmm_promicro
build_src_filter = ${mmm_promicro.build_src_filter}
  +<../examples/kiss_modem/>
