name=InternalFileSystem nRF54
version=0.1.0
author=MeshCore
maintainer=MeshCore
sentence=Adafruit_LittleFS on nRF54L RRAM, as InternalFS
paragraph=Adafruit_LittleFS on nRF54L RRAM, as InternalFS
category=Data Storage
url=https://github.com/meshcore-dev/MeshCore
architectures=*
includes=InternalFileSystem.h
depends=Adafruit Little File System Libraries
