#pragma once

#include "TimeSyncAuth.h"

// Time-sync preference offsets in /com_prefs. The original single-source
// fields occupy 295..428; additional sources are appended from 429 onward.
#define TIME_SYNC_PREFS_ENABLED_OFFSET 295
#define TIME_SYNC_PREFS_CHANNEL_OFFSET 296
#define TIME_SYNC_PREFS_CHANNEL_NAME_OFFSET 329
#define TIME_SYNC_PREFS_DISPLAY_NAME_OFFSET 361
#define TIME_SYNC_PREFS_PUBLIC_KEY_OFFSET 393
#define TIME_SYNC_PREFS_MAX_FORWARD_STEP_OFFSET 425
#define TIME_SYNC_PREFS_EXTRA_DISPLAY_NAMES_OFFSET 429
#define TIME_SYNC_PREFS_EXTRA_PUBLIC_KEYS_OFFSET 525
#define TIME_SYNC_PREFS_NEXT_OFFSET 621

#define TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT (TIME_SYNC_MAX_SOURCES - 1)
#define TIME_SYNC_PREFS_DISPLAY_NAME_SIZE 32
#define TIME_SYNC_PREFS_EXTRA_DISPLAY_NAMES_SIZE \
  (TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT * TIME_SYNC_PREFS_DISPLAY_NAME_SIZE)
#define TIME_SYNC_PREFS_EXTRA_PUBLIC_KEYS_SIZE \
  (TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT * PUB_KEY_SIZE)
