; ----------------- MuziWorks Base Duo (nRF52840 + LR1121) ---------------------
[muziworks_duo]
extends = nrf52_base
board = muziworks-duo
board_build.ldscript = boards/nrf52840_s140_v6.ld
build_flags = ${nrf52_base.build_flags}
  ${sensor_base.build_flags}
  -I src/helpers/nrf52
  -I lib/nrf52/s140_nrf52_6.1.1_API/include
  -I lib/nrf52/s140_nrf52_6.1.1_API/include/nrf52
  -I variants/muziworks_duo
  -D NRF52_PLATFORM
  -D MUZIWORKS_DUO
  -D ENV_INCLUDE_GPS=0
  -D CONFIG_NFCT_PINS_AS_GPIOS=1
  -D RADIO_CLASS=CustomLR1121
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D LORA_TX_POWER=22
  -D MAX_LORA_TX_POWER=22
  -D RX_BOOSTED_GAIN=true
  -D RF_SWITCH_TABLE
  -D P_LORA_DIO_1=40
  -D P_LORA_RESET=42
  -D P_LORA_BUSY=43
  -D P_LORA_NSS=44
  -D P_LORA_SCLK=45
  -D P_LORA_MOSI=46
  -D P_LORA_MISO=47
  -D LR11X0_DIO_AS_RF_SWITCH=true
  -D LR11X0_DIO3_TCXO_VOLTAGE=3.0
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/*.cpp>
  +<helpers/sensors>
  +<../variants/muziworks_duo>
debug_tool = jlink
upload_protocol = nrfutil
lib_deps = ${nrf52_base.lib_deps}
  ${sensor_base.lib_deps}

[env:muziworks_duo_repeater]
extends = muziworks_duo
build_flags =
  ${muziworks_duo.build_flags}
  -D ADVERT_NAME='"MuziDuo Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${muziworks_duo.build_src_filter}
  +<../examples/simple_repeater/*.cpp>

[env:muziworks_duo_room_server]
extends = muziworks_duo
build_flags =
  ${muziworks_duo.build_flags}
  -D ADVERT_NAME='"MuziDuo Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
build_src_filter = ${muziworks_duo.build_src_filter}
  +<../examples/simple_room_server/*.cpp>

[env:muziworks_duo_companion_radio_usb]
extends = muziworks_duo
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 708608
build_flags =
  ${muziworks_duo.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${muziworks_duo.build_src_filter}
  +<helpers/nrf52/*.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${muziworks_duo.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:muziworks_duo_terminal_chat]
extends = muziworks_duo
build_flags =
  ${muziworks_duo.build_flags}
  -D ADVERT_NAME='"MuziDuo Chat"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
build_src_filter = ${muziworks_duo.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${muziworks_duo.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:muziworks_duo_companion_radio_ble]
extends = muziworks_duo
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 708608
build_flags =
  ${muziworks_duo.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D QSPIFLASH=1
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter = ${muziworks_duo.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${muziworks_duo.lib_deps}
  densaugeo/base64 @ ~1.4.0
