[inhero_mr2]
extends = nrf52_base
board = inhero_mr2
board_check = true
board_build.ldscript = boards/nrf52840_s140_v6.ld
build_flags = ${nrf52_base.build_flags}
  -D ENV_INCLUDE_BME280=1
  -I variants/inhero_mr2
  -D INHERO_MR2
  -D PIN_BOARD_SCL=14
  -D PIN_BOARD_SDA=13
  -D PIN_GPS_TX=PIN_SERIAL1_RX
  -D PIN_GPS_RX=PIN_SERIAL1_TX
  -D PIN_GPS_EN=-1
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<../variants/inhero_mr2>
  +<helpers/sensors>
lib_deps =
  ${nrf52_base.lib_deps}
  adafruit/Adafruit BME280 Library @ ^2.3.0
  https://github.com/adafruit/Adafruit_bq25798.git
  sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.27
upload_protocol = nrfutil
debug_tool = cmsis-dap


[env:Inhero_MR2_repeater]
extends = inhero_mr2
build_flags =
  ${inhero_mr2.build_flags}
  -D ADVERT_NAME='"Inhero_MR2 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${inhero_mr2.build_src_filter}
  +<../examples/simple_repeater>

[env:Inhero_MR2_repeater_bridge_rs232]
extends = inhero_mr2
build_flags =
  ${inhero_mr2.build_flags}
  -D ADVERT_NAME='"Inhero_MR2 RS232 Bridge"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D WITH_RS232_BRIDGE=Serial2
  -D WITH_RS232_BRIDGE_RX=PIN_SERIAL2_RX
  -D WITH_RS232_BRIDGE_TX=PIN_SERIAL2_TX
build_src_filter = ${inhero_mr2.build_src_filter}
  +<helpers/bridges/RS232Bridge.cpp>
  +<../examples/simple_repeater>

[env:Inhero_MR2_sensor]
extends = inhero_mr2
build_flags =
  ${inhero_mr2.build_flags}
  -D ADVERT_NAME='"Inhero_MR2 Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
build_src_filter = ${inhero_mr2.build_src_filter}
  +<../examples/simple_sensor>
