[ESP32_S3_Supermini]
extends=esp32_base
board=esp32-s3-zero
board_build.partitions = huge_app.csv ; FW weight: ~1.7MB, but default partition is only ~1.3MB. Remove OTA and raise APP partition upto 3MB
;build_type = debug
;debug_tool = esp-builtin
monitor_echo = yes
;monitor_filters = esp32_exception_decoder

build_flags =
	${esp32_base.build_flags}
	${sensor_base.build_flags}
	-I variants/ESP32_S3_Supermini
	-D ESP32_CPU_FREQ=80
	-D BOARD_HAS_PSRAM

	; SPI-0 / LoRa (LR1121-HF)
	-D PIN_SPI_MISO=11
	-D PIN_SPI_MOSI=10
	-D PIN_SPI_SCK=9
	-D PIN_SPI_NSS=8

	-D P_LORA_MISO=PIN_SPI_MISO
	-D P_LORA_MOSI=PIN_SPI_MOSI
	-D P_LORA_SCLK=PIN_SPI_SCK
	-D P_LORA_NSS=PIN_SPI_NSS
	-D P_LORA_DIO_1=1           ; IRQ
	-D P_LORA_RESET=12
	-D P_LORA_BUSY=13

	-D LORA_TX_POWER=22             ; Max 14 for 2.4GHz or 22 for <900MHz
	-D LR11X0_DIO3_TCXO_VOLTAGE=3.0
	-D LR11X0_DIO_AS_RF_SWITCH=1
	-D RX_BOOSTED_GAIN=1

	; Wire/i2c
	-D PIN_BOARD_SDA=4
	-D PIN_BOARD_SCL=5
	; 2nd wire for sensors
	;-D ENV_PIN_SDA=4
	;-D ENV_PIN_SCL=5

	; Serial / UART (For GPS)
	-D ENV_INCLUDE_GPS=0 ; Disable GPS support
	;-D PIN_GPS_TX=6
	;-D PIN_GPS_RX=7
	;-D PIN_GPS_EN=-1
	;-D GPS_BAUD_RATE=9600
	;-D ENV_SKIP_GPS_DETECT
	;-D FORCE_GPS_ALIVE

	; Builtin LEDs
	-D LED_PIN=48
	-D LED_STATE_ON=0
	-D PIN_LED=LED_PIN
	-D LED_RED=LED_PIN
	-D LED_BLUE=-1

	; Button
	-D PIN_BUTTON1=0
	-D BUTTON_PIN=PIN_BUTTON1
	-D PIN_USER_BTN=PIN_BUTTON1

	; Battery ADC
	-D PIN_VBAT_READ=16
	-D ADC_MULTIPLIER=2.085 ; BAT- -> 1M -> ADC -> 1M -> BAT+

	; SPI-1 / Display
	-D PIN_SPI1_SCK=45
	-D PIN_SPI1_MISO=47 ; NC
	-D PIN_SPI1_MOSI=46

	-D UI_RECENT_LIST_SIZE=4
	;-D UI_SENSORS_PAGE=1
	-D AUTO_OFF_MILLIS=0       ; Disable display off (eink wont need it)
	-D BOOT_SCREEN_MILLIS=1000 ; Reduce boot time

	-D DISPLAY_CLASS=GxEPDDisplay
	-D EINK_DISPLAY_MODEL=GxEPD2_290_BS
	-D EINK_LOGICAL_W=128
	-D EINK_LOGICAL_H=296
	-D EINK_SCALE_X=1.0f
	-D EINK_SCALE_Y=1.0f
	-D EINK_X_OFFSET=0
	-D EINK_Y_OFFSET=0

	-D PIN_DISPLAY_SCLK=PIN_SPI1_SCK
	-D PIN_DISPLAY_MISO=PIN_SPI1_MISO
	-D PIN_DISPLAY_MOSI=PIN_SPI1_MOSI
	-D PIN_DISPLAY_CS=42
	-D PIN_DISPLAY_DC=41
	-D PIN_DISPLAY_RST=40
	-D PIN_DISPLAY_BUSY=39

	; Logging
	-D DISABLE_DIAGNOSTIC_OUTPUT ; GxEPD2 debug off
	;-D BLE_DEBUG_LOGGING=1
	;-D MESH_PACKET_LOGGING=1
	;-D MESH_DEBUG=1
	;-D RADIOLIB_DEBUG_BASIC=1
	;-D RADIOLIB_DEBUG_PROTOCOL=1
	;-D RADIOLIB_DEBUG_SPI=0
	;-D RADIOLIB_VERBOSE_ASSERT=1
	;-D CORE_DEBUG_LEVEL=3
	;-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D ARDUINO_USB_MODE=1

build_src_filter=${esp32_base.build_src_filter}
	+<../variants/ESP32_S3_Supermini>
	+<helpers/sensors>
	; Display
	+<helpers/ui/GxEPDDisplay.cpp>
	+<helpers/ui/MomentaryButton.cpp>
	+<../examples/companion_radio/*.cpp>
	+<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
	${esp32_base.lib_deps}
	${sensor_base.lib_deps}
	bakercp/CRC32
	;densaugeo/base64
	;end2endzone/NonBlockingRTTTL
	;zinggjm/GxEPD2   ; ePaper displays drivers
	GxEPD2

[env:ESP32_S3_Supermini_repeater]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-D ADVERT_NAME='"Meshcore Repeater"'
	-D ADVERT_LAT=0.0
	-D ADVERT_LON=0.0
	-D ADMIN_PASSWORD='"password"'
	-D MAX_NEIGHBOURS=50
build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<../examples/simple_repeater>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	${esp32_ota.lib_deps}
	bakercp/CRC32 @ ^2.0.0

[env:ESP32_S3_Supermini_bridge_rs232]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-D ADVERT_NAME='"RS232 Bridge"'
	-D ADVERT_LAT=0.0
	-D ADVERT_LON=0.0
	-D ADMIN_PASSWORD='"password"'
	-D MAX_NEIGHBOURS=50

	-D WITH_RS232_BRIDGE=Serial2 ; TODO
	-D WITH_RS232_BRIDGE_RX=5
	-D WITH_RS232_BRIDGE_TX=6

build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<helpers/bridges/RS232Bridge.cpp>
	+<../examples/simple_repeater>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	${esp32_ota.lib_deps}

[env:ESP32_S3_Supermini_room_server]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-D ADVERT_NAME='"Room server"'
	-D ADVERT_LAT=0.0
	-D ADVERT_LON=0.0
	-D ADMIN_PASSWORD='"password"'
	-D ROOM_PASSWORD='"hello"'
build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<../examples/simple_room_server>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	${esp32_ota.lib_deps}

[env:ESP32_S3_Supermini_terminal_chat]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-D MAX_CONTACTS=350
	-D MAX_GROUP_CHANNELS=1
build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<../examples/simple_secure_chat/main.cpp>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	densaugeo/base64 @ ~1.4.0

[env:ESP32_S3_Supermini_sensor]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-D ADVERT_NAME='"Meshcore Sensor"'
	-D ADVERT_LAT=0.0
	-D ADVERT_LON=0.0
	-D ADMIN_PASSWORD='"password"'
build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<../examples/simple_sensor>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	${esp32_ota.lib_deps}

[env:ESP32_S3_Supermini_companion_radio_uni]
extends=ESP32_S3_Supermini
build_flags =
	${ESP32_S3_Supermini.build_flags}
	-I examples/companion_radio/ui-new
	-D MAX_CONTACTS=350
	-D MAX_GROUP_CHANNELS=40
	-D OFFLINE_QUEUE_SIZE=256
	-D WITH_COMPANION_CLI
	-D WITH_WIFI_SWITCHING
build_src_filter=${ESP32_S3_Supermini.build_src_filter}
	+<helpers/esp32/*.cpp>
	+<../examples/companion_radio/*.cpp>
	+<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
	${ESP32_S3_Supermini.lib_deps}
	densaugeo/base64 @ ~1.4.0
