[Ebyte_E77]
extends = stm32_base
board = ebyte_e77_dev
board_upload.maximum_size = 229376 ; 32kb for FS
build_flags = ${stm32_base.build_flags}
  -D RADIO_CLASS=CustomSTM32WLx
  -D WRAPPER_CLASS=CustomSTM32WLxWrapper
  -D SPI_INTERFACES_COUNT=0
  -D RX_BOOSTED_GAIN=true
;  -D STM32WL_TCXO_VOLTAGE=1.6 ; defaults to 0 if undef
;  -D LORA_TX_POWER=14 ; Defaults to 22 for HP, 14 is for LP version
  -D LORA_TX_POWER=22 ; Enable 22dBm transmission
  -D MAX_LORA_TX_POWER=22 ; Allow setting up to 22dBm in companion radio
  -I variants/ebyte_e77
build_src_filter = ${stm32_base.build_src_filter}
  +<../variants/ebyte_e77>

[env:Ebyte_E77_repeater]
extends = Ebyte_E77
build_flags = ${Ebyte_E77.build_flags}
  -D ADVERT_NAME='"ebyte_e77 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${Ebyte_E77.build_src_filter}
  +<../examples/simple_repeater>

[env:Ebyte_E77_sensor]
extends = Ebyte_E77
build_flags = ${Ebyte_E77.build_flags}
  -D ADVERT_NAME='"ebyte_e77 Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${Ebyte_E77.build_src_filter}
  +<../examples/simple_sensor>

[env:Ebyte_E77_companion_radio_usb]
extends = Ebyte_E77
build_flags = ${Ebyte_E77.build_flags}
;  -D FORMAT_FS=true
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
  -D MAX_LORA_TX_POWER=22
build_src_filter = ${Ebyte_E77.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${Ebyte_E77.lib_deps}
  densaugeo/base64 @ ~1.4.0
