name: Run Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Run Unit Tests
        run: pio test -e native -vv

      - name: Upload Test Results
        # Upload test results even if the test step failed.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .pio/build/native/
